# 工作目录
# 使用 . 或绝对路径，请注意 `tmp_dir` 目录必须在 `root` 目录下
root = "."
testdata_dir = "testdata"
tmp_dir = "build"

[build]
  args_bin = []
  bin = "build\\VitaTaskWeb.exe"
  cmd = "go build -o ./build/VitaTaskWeb.exe ./cmd/web/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "uploads", "docker", "logs", "build"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  # 最后的字符解释(仅适用于Windows)
  # \n 是换行符，rem是注释语句
  full_bin = "./build/VitaTaskWeb.exe -f ./config/app.yaml\nrem "
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  # 发送中断信号后的延迟
  kill_delay = "10s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 5000
  send_interrupt = false
  # 发生构建错误时，停止运行旧的二进制文件。
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  # 退出时删除tmp目录
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
