app:
  port: 8081
  host:
  debug: true

mysql:
  user: vitatask
  password: vitatask
  host: 127.0.0.1
  port: 3306
  dbname: vita_task
  prefix: vt_

mongo:
  username: root
  password: root
  host: 127.0.0.1
  port: 27017
  dbname: vita_task

redis:
  host: 127.0.0.1
  port: 6379
  auth:

jwt:
  key: zZf6CQefPczfoDUDLTc0k3WtnaP1018xeFwP50AAFs2yB7Ng
  expire: 28800
  issuer: VitaTaskGo

member:
  defaultPass: Ab123456

gateway:
  port: 8082
  host: